services:
  db:
    ports:
      - 5432:5432
    image: postgres:17
    # image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  dartbackend:
    build: .
    ports:
      - 13000:3000
      - 18080:8080

    environment:
      DB_HOST: db
      MQTT_HOST: mosquitto
      DB_NAME: ${POSTGRES_DB}
      TABLE_NAME: ${TABLE_NAME}
    volumes:
      - ftp_data:/ftp/zebra
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/c/data
      - ./docker/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true
    tty: true
    restart: always

  ftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - "22:22"
    volumes:
      - ftp_data:/home/zebra
    command: ${FTP_USER}:${FTP_PASSWORD}:1000:1000
    restart: always

volumes:
  ftp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker/ftp
      # device: /home/scalextric/Desktop/dmo-scalextric/docker/ftp
  db:
